Database scheme
LifeCalendarTeam/life_calendar pull request #4
Opened 2020-10-10 16:22 UTC by VladimirKoryakin

I think, I've rebased this branch so we can finally merge it. Sorry for closing previous PR, it was my fault

2020-10-10 17:04 UTC, kolayne requested changes
1. Your image file has a trailing space character before the extension. I don't think it's supposed to be named this way
2. Formally fields order is a part of a database scheme and the order of fields in the `users` table in the two schemes differ. I think it's an issue

2020-10-10 17:11 UTC, VladimirKoryakin commented
Oh... I'll fix it and rebase the branch again. Thank you!

2020-10-10 17:21 UTC, VladimirKoryakin commented
Now everything is finally fine (I hope). Thank you for your help and constructive comments!

2020-10-10 17:32 UTC, kolayne approved these changes

2020-10-11 15:44 UTC, tanya-kta approved these changes

2020-10-12 00:44 UTC, FixedOctocat approved these changes

2020-10-12 11:43 UTC, merged